import { createAgendaEvento, deleteAgendaEvento, listAgendaEventos, updateAgendaEvento } from '../../../services/agendaService.js';
import { listRepertorios } from '../../../services/repertoriosService.js';
import { hasPermission } from '../../auth/permissions.js';

export async function AgendaPage({ session } = {}) {
  const page = document.createElement('section');
  page.className = 'page agenda-page';
  const canEdit = hasPermission(session, 'agenda', 'can_create');
  let cursor = new Date(); cursor.setDate(1); cursor.setHours(0, 0, 0, 0);
  page.innerHTML = `<header class="agenda-hero"><div><span class="agenda-kicker">Organizacao musical</span><h1>Agenda</h1><p data-page-info>Planeje compromissos, registre orientacoes e vincule repertorios para cada evento.</p></div></header><section class="agenda-layout"><div class="agenda-calendar-panel"><div class="agenda-calendar-toolbar"><button class="nav-button" data-action="previous" type="button">Anterior</button><h2 data-role="month"></h2><button class="nav-button" data-action="next" type="button">Proximo</button></div><div class="agenda-weekdays">${['Dom','Seg','Ter','Qua','Qui','Sex','Sab'].map((day) => `<span>${day}</span>`).join('')}</div><div class="agenda-grid" data-role="calendar"></div></div></section>${canEdit ? `<div class="agenda-modal" data-role="modal" hidden><div class="agenda-modal-backdrop" data-action="close"></div><div class="agenda-modal-dialog" role="dialog" aria-modal="true">${createAgendaForm()}<button class="agenda-modal-close" type="button" data-action="close" aria-label="Fechar">&times;</button></div></div>` : ''}`;
  const calendar = page.querySelector('[data-role="calendar"]'); const month = page.querySelector('[data-role="month"]');
  let repertorios = []; let eventos = []; let editingEvent = null;
  const render = async () => { const from = new Date(cursor); const to = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1); month.textContent = new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(cursor); calendar.innerHTML = '<p class="page-status">Carregando agenda...</p>'; const { data, error } = await listAgendaEventos(from.toISOString(), to.toISOString()); if (error) { calendar.innerHTML = `<p class="page-status error">${escapeHtml(error.message)}</p>`; return; } eventos = data || []; renderCalendar(calendar, cursor, eventos); };
  page.querySelector('[data-action="previous"]').addEventListener('click', () => { cursor.setMonth(cursor.getMonth() - 1); render(); }); page.querySelector('[data-action="next"]').addEventListener('click', () => { cursor.setMonth(cursor.getMonth() + 1); render(); });
  if (canEdit) {
    const { data } = await listRepertorios(); repertorios = data || [];
    const modal = page.querySelector('[data-role="modal"]'); const form = page.querySelector('.agenda-form');
    const repertoireSearch = form.querySelector('[name="repertorio_busca"]'); const repertoireId = form.querySelector('[name="repertorio_id"]'); const repertoireResults = form.querySelector('[data-role="repertorio-results"]');
    const updateRepertoireResults = () => { const term = normalize(repertoireSearch.value); const matches = repertorios.filter((item) => normalize(item.nome || item.titulo).includes(term)).slice(0, 6); repertoireResults.hidden = !term || !matches.length; repertoireResults.innerHTML = matches.map((item) => `<button type="button" data-repertorio-id="${escapeHtml(item.id)}">${escapeHtml(item.nome || item.titulo || '')}</button>`).join(''); };
    repertoireSearch.addEventListener('input', updateRepertoireResults); repertoireResults.addEventListener('click', (event) => { const button = event.target.closest('[data-repertorio-id]'); if (!button) return; const repertorio = repertorios.find((item) => item.id === button.dataset.repertorioId); repertoireId.value = repertorio.id; repertoireSearch.value = repertorio.nome || repertorio.titulo || ''; repertoireResults.hidden = true; });
    const openForm = (event = null, date = new Date()) => { editingEvent = event; form.reset(); const linked = event?.agenda_evento_repertorios?.[0]; const repertorio = repertorios.find((item) => item.id === linked?.repertorio_id); repertoireId.value = repertorio?.id || ''; repertoireSearch.value = repertorio?.nome || repertorio?.titulo || ''; form.querySelector('h2').textContent = event ? 'Editar compromisso' : 'Novo compromisso'; form.titulo.value = event?.titulo || ''; form.inicio.value = toLocalInputValue(event?.inicio || date); form.fim.value = event?.fim ? toLocalInputValue(event.fim) : ''; form.local.value = event?.local || ''; form.descricao.value = event?.descricao || ''; modal.hidden = false; form.titulo.focus(); };
    const closeForm = () => { modal.hidden = true; editingEvent = null; };
    page.addEventListener('click', (event) => { const day = event.target.closest('[data-agenda-day]'); const eventButton = event.target.closest('[data-agenda-event]'); if (eventButton) openForm(eventos.find((item) => item.id === eventButton.dataset.agendaEvent)); else if (day) openForm(null, new Date(`${day.dataset.agendaDay}T09:00`)); if (event.target.closest('[data-action="close"]')) closeForm(); });
    form.addEventListener('submit', async (event) => { event.preventDefault(); const values = new FormData(form); const payload = { titulo: values.get('titulo'), descricao: values.get('descricao') || null, local: values.get('local') || null, inicio: new Date(values.get('inicio')).toISOString(), fim: values.get('fim') ? new Date(values.get('fim')).toISOString() : null, status: editingEvent?.status || 'pendente', responsavel: null, orientacoes: null }; const ids = repertoireId.value ? [repertoireId.value] : []; const { error } = editingEvent ? await updateAgendaEvento(editingEvent.id, payload, ids) : await createAgendaEvento(payload, ids); if (error) { form.querySelector('[data-role="message"]').textContent = error.message; return; } closeForm(); await render(); });
  }
  await render(); return page;
}
function createAgendaForm() { return `<form class="form agenda-form"><h2>Novo compromisso</h2><label>Titulo<input required name="titulo" placeholder="Ex: Culto de domingo"></label><div class="agenda-form-row"><label>Inicio<input required type="datetime-local" name="inicio"></label><label>Termino<input type="datetime-local" name="fim"></label></div><label>Local<input name="local" placeholder="Ex: Templo sede"></label><label>Buscar repertorio<input type="search" name="repertorio_busca" autocomplete="off" placeholder="Nome do repertorio"></label><input type="hidden" name="repertorio_id"><div class="agenda-repertorio-results" data-role="repertorio-results" hidden></div><label>Descricao<textarea name="descricao" rows="3"></textarea></label><button class="button" type="submit">Salvar compromisso</button><p class="form-message" data-role="message" aria-live="polite"></p></form>`; }
function renderCalendar(container, month, eventos) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const last = new Date(month.getFullYear(), month.getMonth() + 1, 0); const cells = Array.from({ length: first.getDay() + last.getDate() }, (_, index) => index - first.getDay() + 1); container.innerHTML = cells.map((day) => day < 1 ? '<div class="agenda-day is-empty"></div>' : `<article class="agenda-day" data-agenda-day="${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}"><strong>${day}</strong>${eventos.filter((event) => new Date(event.inicio).getDate() === day).map((event) => `<button class="agenda-event is-${event.status}" data-agenda-event="${escapeHtml(event.id)}" title="${escapeHtml(event.local || '')}">${escapeHtml(new Date(event.inicio).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }))} ${escapeHtml(event.titulo)}</button>`).join('')}</article>`).join(''); }
function toLocalInputValue(value) { const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function normalize(value) { return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); }
function escapeHtml(value) { return String(value || '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }
