import { createAgendaEvento, listAgendaEventos } from '../../../services/agendaService.js';
import { listRepertorios } from '../../../services/repertoriosService.js';
import { hasPermission } from '../../auth/permissions.js';

export async function AgendaPage({ session } = {}) {
  const page = document.createElement('section');
  page.className = 'page agenda-page';
  const canEdit = hasPermission(session, 'agenda', 'can_create');
  let cursor = new Date(); cursor.setDate(1); cursor.setHours(0, 0, 0, 0);
  page.innerHTML = `<header class="agenda-hero"><div><span class="agenda-kicker">Organizacao musical</span><h1>Agenda</h1><p data-page-info>Planeje compromissos, registre orientacoes e vincule repertorios para cada evento.</p></div></header><section class="agenda-layout"><div class="agenda-calendar-panel"><div class="agenda-calendar-toolbar"><button class="nav-button" data-action="previous" type="button">Anterior</button><h2 data-role="month"></h2><button class="nav-button" data-action="next" type="button">Proximo</button></div><div class="agenda-weekdays">${['Dom','Seg','Ter','Qua','Qui','Sex','Sab'].map((day) => `<span>${day}</span>`).join('')}</div><div class="agenda-grid" data-role="calendar"></div></div><aside class="agenda-side"><section class="agenda-upcoming"><h2>Proximos compromissos</h2><div data-role="upcoming"></div></section>${canEdit ? createAgendaForm() : ''}</aside></section>`;
  const calendar = page.querySelector('[data-role="calendar"]'); const month = page.querySelector('[data-role="month"]'); const upcoming = page.querySelector('[data-role="upcoming"]');
  let repertorios = []; let eventos = [];
  const render = async () => { const from = new Date(cursor); const to = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1); month.textContent = new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(cursor); calendar.innerHTML = '<p class="page-status">Carregando agenda...</p>'; const { data, error } = await listAgendaEventos(from.toISOString(), to.toISOString()); if (error) { calendar.innerHTML = `<p class="page-status error">${escapeHtml(error.message)}</p>`; return; } eventos = data || []; renderCalendar(calendar, cursor, eventos); renderUpcoming(upcoming, eventos); };
  page.querySelector('[data-action="previous"]').addEventListener('click', () => { cursor.setMonth(cursor.getMonth() - 1); render(); }); page.querySelector('[data-action="next"]').addEventListener('click', () => { cursor.setMonth(cursor.getMonth() + 1); render(); });
  if (canEdit) { const { data } = await listRepertorios(); repertorios = data || []; const select = page.querySelector('[name="repertorios"]'); select.innerHTML = repertorios.map((item) => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.nome || item.titulo || '')}</option>`).join(''); page.querySelector('.agenda-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const { error } = await createAgendaEvento({ titulo: values.get('titulo'), descricao: values.get('descricao') || null, local: values.get('local') || null, inicio: new Date(values.get('inicio')).toISOString(), fim: values.get('fim') ? new Date(values.get('fim')).toISOString() : null, status: values.get('status'), responsavel: values.get('responsavel') || null, orientacoes: values.get('orientacoes') || null }, [...select.selectedOptions].map((option) => option.value)); const message = form.querySelector('[data-role="message"]'); message.textContent = error ? error.message : 'Compromisso salvo na agenda.'; if (!error) { form.reset(); await render(); } }); }
  await render(); return page;
}
function createAgendaForm() { return `<form class="form agenda-form"><h2>Novo compromisso</h2><label>Titulo<input required name="titulo" placeholder="Ex: Culto de domingo"></label><div class="agenda-form-row"><label>Inicio<input required type="datetime-local" name="inicio"></label><label>Termino<input type="datetime-local" name="fim"></label></div><label>Local<input name="local" placeholder="Ex: Templo sede"></label><div class="agenda-form-row"><label>Status<select name="status"><option value="pendente">Pendente</option><option value="confirmado">Confirmado</option><option value="cancelado">Cancelado</option></select></label><label>Responsavel<input name="responsavel" placeholder="Nome da lideranca"></label></div><label>Repertorios vinculados<select name="repertorios" multiple size="4"></select></label><label>Descricao<textarea name="descricao" rows="3"></textarea></label><label>Orientacoes<textarea name="orientacoes" rows="3" placeholder="Passagem de som, escala, roupa ou avisos"></textarea></label><button class="button" type="submit">Salvar compromisso</button><p class="form-message" data-role="message" aria-live="polite"></p></form>`; }
function renderCalendar(container, month, eventos) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const last = new Date(month.getFullYear(), month.getMonth() + 1, 0); const cells = Array.from({ length: first.getDay() + last.getDate() }, (_, index) => index - first.getDay() + 1); container.innerHTML = cells.map((day) => day < 1 ? '<div class="agenda-day is-empty"></div>' : `<article class="agenda-day"><strong>${day}</strong>${eventos.filter((event) => new Date(event.inicio).getDate() === day).map((event) => `<button class="agenda-event is-${event.status}" title="${escapeHtml(event.local || '')}">${escapeHtml(new Date(event.inicio).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }))} ${escapeHtml(event.titulo)}</button>`).join('')}</article>`).join(''); }
function renderUpcoming(container, eventos) { const now = new Date(); const next = eventos.filter((event) => new Date(event.inicio) >= now).slice(0, 5); container.innerHTML = next.length ? next.map((event) => `<article><strong>${escapeHtml(event.titulo)}</strong><span>${new Date(event.inicio).toLocaleString('pt-BR')} · ${escapeHtml(event.local || 'Local a definir')}</span><small>${(event.agenda_evento_repertorios || []).map((item) => item.repertorios?.nome).filter(Boolean).join(' · ') || 'Sem repertorio vinculado'}</small></article>`).join('') : '<p>Nenhum compromisso neste mes.</p>'; }
function escapeHtml(value) { return String(value || '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }
